name: discord notify

on:
  push:
    branches: [ "**" ]

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: send push to discord
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"push: auths-RNG@${{ github.ref_name }}\ncommit: ${{ github.sha }}\nurl: https://git.authsrng.xyz/auths-RNG.git/commit/?h=${{ github.ref_name }}&id=${{ github.sha }}\nauthor: ${{ github.actor }}\nmessage: ${{ github.event.head_commit.message }}\n\n\`\`\`\ngit.authsrng.xyz is cached every 5 minutes, and commit URLs will usually work approximately 5 minutes of this commit time exactly. please wait 3 - 5 minutes before you open up the URL! if the git site is down, please ping or DM auth immediately!\n\`\`\`\"}" \
            ${{ secrets.DISCORD_WEBHOOK }}